# Generated by Django 4.2.4 on 2023-08-24 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=250)),
                ('u_password', models.CharField(max_length=12)),
                ('u_repassword', models.CharField(max_length=12)),
                ('u_mail', models.CharField(max_length=30)),
            ],
        ),
    ]
