# Generated by Django 4.2.4 on 2023-08-09 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=100, unique=True)),
                ('c_image', models.ImageField(upload_to='ctgry_Image')),
                ('c_slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'catagory',
                'verbose_name_plural': 'catagories',
                'ordering': ('c_name',),
            },
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('p_price', models.IntegerField()),
                ('p_image', models.ImageField(upload_to='Pdt_Image')),
                ('p_desc', models.TextField()),
                ('p_stock', models.IntegerField()),
                ('p_available', models.BooleanField()),
                ('p_slug', models.SlugField(max_length=100, unique=True)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.catagory')),
            ],
        ),
    ]
